### ISSUE TITLE
Extra Lines

### ISSUE THREAD

**Issue by ssdpress** [seriema/gdocs2md-addon#2]
First, thank you for the add-on this appears to go quite far is solving something I've been struggling with.

When I export a doc it seems to add an extra line break after each line in my doc.  (I'm trying to export a bulleted list.)  I just grepped out the extra lines, but then it also removed the necessary blank lines between a header and the list.  Looking to get something like this:

```
**Header**

* line 1
* line 2
   * indent 1
   * indent 2
      * second indent 1
* line 3
```

In the markdown systems I'm using, if you don't have the line break between the header and the bullets it prints the bullets as *'s with no spaces/indents instead of formatting them as expected.

Not sure if I'm just doing something wrong.

Thanks in advance.

**Comment by seriema** [comment]
Thank you for using it!

The conversion is actually done by the [gdocs2md script](https://github.com/mangini/gdocs2md) which I don't control. They seem to have an issue logged since 2013 that might be what you described: https://github.com/mangini/gdocs2md/issues/13

If there's enough interest I'll fork that project and start fixing these issues myself or with the help of PR's.

**Comment by seriema** [comment]
I'd like to fork the project, but I'm a bit busy with other side projects atm. Unless someone wants to contribute fixes this issue will just be needlessly open, so I'll just close it.
